// Generated by CoffeeScript 2.3.2
(function() {
  // Ncurl -u admin:$PASSWORD -i -H 'X-Requested-By: ambari' -X PUT -d '{"HostRoles": {"state": "STARTED"}}' http://AMBARI_SERVER_HOST:8080/api/v1/clusters/CLUSTER_NAME/hosts/NEW_HOST_ADDED/host_components/GANGLIA_MONITOR

  // # Ambari Start Component host

  // Add a host to an ambari cluster [REST API v2](https://github.com/apache/ambari/blob/trunk/ambari-server/docs/api/v1)
  // The node should already exist in ambari.

  // * `password` (string)
  //   Ambari Administrator password.
  // * `url` (string)   
  //   Ambari External URL.
  // * `username` (string)
  //   Ambari Administrator username.
  // * `cluster_name` (string)   
  //   Name of the cluster, optional
  // * `hostname` (string)   
  //   The name of host to start the component to.
  // * `name` (string)   
  //   The name of component to start.

  // ## Exemple

  // ```js
  // .hosts.component_add({
  //   "username": 'ambari_admin',
  //   "password": 'ambari_secret',
  //   "url": "http://ambari.server.com",
  //   "component_name": 'NAMENODE'
  //   "hostname": 'master1.metal.ryba'
  //   }
  // }, function(err, status){
  //   console.log( err ? err.message : "Component" + options.component_name + "Started: " + status)
  // })
  // ```

  // ## Source Code
  var utils;

  module.exports = function(options, callback) {
    var do_end, err, error, hostname, opts, path, port, status;
    if (typeof options.options === 'object') {
      options = options.options;
    }
    error = null;
    status = false;
    if (options.debug == null) {
      options.debug = false;
    }
    do_end = function() {
      if (callback != null) {
        return callback(error, status);
      }
      return new Promise(function(fullfil, reject) {
        if (error != null) {
          reject(error);
        }
        return fullfil(status);
      });
    };
    try {
      if (options.component_name == null) {
        options.component_name = options.name;
      }
      if (!options.username) {
        throw Error('Required Options: username');
      }
      if (!options.password) {
        throw Error('Required Options: password');
      }
      if (!options.url) {
        throw Error('Required Options: url');
      }
      if (!options.component_name) {
        throw Error('Required Options: component_name');
      }
      if (!options.hostname) {
        throw Error('Required Options: hostname');
      }
      if (!options.cluster_name) {
        throw Error('Required Options: cluster_name');
      }
      [hostname, port] = options.url.split("://")[1].split(':');
      if (options.sslEnabled == null) {
        options.sslEnabled = options.url.split('://')[0] === 'https';
      }
      path = `/api/v1/clusters/${options.cluster_name}/hosts/${options.hostname}/host_components/${options.component_name}`;
      opts = {
        hostname: hostname,
        port: port,
        rejectUnauthorized: false,
        headers: utils.headers(options),
        sslEnabled: options.sslEnabled
      };
      opts['method'] = 'GET';
      opts.path = `${path}`;
      return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
        try {
          if (err) {
            //"":{""
            //Kerberos Service Check","command":"KERBEROS_SERVICE_CHECK","operation_level":{"level":"CLUSTER","cluster_name":"ryba_test"}},"Requests/resource_filters":[{"service_name":"KERBEROS"}]}	
            throw err;
          }
          response = JSON.parse(response);
          if (statusCode !== 200) {
            throw Error(response.message);
          }
          if (response['HostRoles']['state'] === 'INSTALL_FAILED') {
            throw Error(`Can not start ${options.component_name} as it is in INSTALL_FAILED state`);
          }
          status = false;
          if (typeof this.log === "function") {
            this.log({
              message: `Starting Service ${options.component_name} via API`,
              level: 'INFO',
              module: 'ryba-ambari-actions/hosts/component_start'
            });
          }
          if (typeof this.log === "function") {
            this.log({
              message: `${opts.path}`,
              level: 'DEBUG',
              module: 'ryba-ambari-actions/hosts/component_start'
            });
          }
          if (typeof this.log === "function") {
            this.log({
              message: `component ${options.component_name} already in STARTED state`,
              level: 'INFO',
              module: 'ryba-ambari-actions/hosts/component_start'
            });
          }
          if (response['HostRoles']['state'] === 'STARTED') {
            return do_end();
          }
          opts['method'] = 'PUT';
          opts.content = JSON.stringify({
            RequestInfo: {
              context: `Service Start ${options.component_name} (API)`
            },
            HostRoles: {
              state: 'STARTED'
            }
          });
          return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
            error = err;
            if (!err) {
              status = true;
            }
            return do_end();
          });
        } catch (error1) {
          err = error1;
          error = err;
          return do_end();
        }
      });
    } catch (error1) {
      err = error1;
      error = err;
      return do_end();
    }
  };

  // ## Depencendies
  utils = require('../utils');

}).call(this);
