// Generated by CoffeeScript 2.1.1
// Ncurl -u admin:$PASSWORD -i -H 'X-Requested-By: ambari' -X PUT -d '{"HostRoles": {"state": "STARTED"}}' http://AMBARI_SERVER_HOST:8080/api/v1/clusters/CLUSTER_NAME/hosts/NEW_HOST_ADDED/host_components/GANGLIA_MONITOR

// # Ambari Install Component host

// Install a component's service on a host [REST API v2](https://github.com/apache/ambari/blob/trunk/ambari-server/docs/api/v1)
// The service and the node should exist

// * `password` (string)
//   Ambari Administrator password.
// * `url` (string)   
//   Ambari External URL.
// * `username` (string)
//   Ambari Administrator username.
// * `cluster_name` (string)   
//   Name of the cluster, optional
// * `hostname` (string)   
//   The name of host to start the component to.
// * `name` (string)   
//   The name of component to start.
// * `wait` (boolean)   
//   Use the request Id return by install to wait until it finished. If true
// the status will be true if the final state is `FINISHED`, or false if in `INSTALL_FAILED`
// state. Default to false.

// ## Exemple

// ```js
// .hosts.component_install({
//   "username": 'ambari_admin',
//   "password": 'ambari_secret',
//   "url": "http://ambari.server.com",
//   "component_name": 'NAMENODE'
//   "hostname": 'master1.metal.ryba'
//   }
// }, function(err, status){
//   console.log( err ? err.message : "Component" + options.component_name + "Installed: " + status)
// })
// ```

// ## Source Code
var utils;

module.exports = function(options, callback) {
  var do_end, err, error, hostname, interval, opts, path, port, status;
  if (typeof options.options === 'object') {
    options = options.options;
  }
  error = null;
  status = false;
  if (options.debug == null) {
    options.debug = false;
  }
  if (options.stdout == null) {
    options.stdout = process.stdout;
  }
  interval = null;
  do_end = function() {
    if (interval != null) {
      clearInterval(interval);
    }
    if (callback != null) {
      return callback(error, status);
    }
    return new Promise(function(fullfil, reject) {
      if (error != null) {
        reject(error);
      }
      return fullfil(status);
    });
  };
  try {
    if (options.component_name == null) {
      options.component_name = options.name;
    }
    if (!options.username) {
      throw Error('Required Options: username');
    }
    if (!options.password) {
      throw Error('Required Options: password');
    }
    if (!options.url) {
      throw Error('Required Options: url');
    }
    if (!options.component_name) {
      throw Error('Required Options: component_name');
    }
    if (!options.hostname) {
      throw Error('Required Options: hostname');
    }
    if (!options.cluster_name) {
      throw Error('Required Options: cluster_name');
    }
    if (options.wait == null) {
      options.wait = true;
    }
    [hostname, port] = options.url.split("://")[1].split(':');
    if (options.sslEnabled == null) {
      options.sslEnabled = options.url.split('://')[0] === 'https';
    }
    path = `/api/v1/clusters/${options.cluster_name}/hosts/${options.hostname}/host_components/${options.component_name}`;
    opts = {
      hostname: hostname,
      port: port,
      rejectUnauthorized: false,
      headers: utils.headers(options),
      sslEnabled: options.sslEnabled
    };
    opts['method'] = 'GET';
    opts.path = `${path}`;
    return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
      var ref, ref1, ref2;
      try {
        if (err) {
          throw err;
        }
        response = JSON.parse(response);
        if (statusCode !== 200) {
          throw Error(response.message);
        }
        if (!((ref = response['HostRoles']['state']) === 'INIT')) {
          if (parseInt(statusCode) === 200) {
            if (typeof this.log === "function") {
              this.log({
                message: `Component NOT in INIT state  hostname:${options.hostname} component: ${options.component_name}`,
                level: 'INFO',
                module: 'ryba-ambari-actions/hosts/component_install'
              });
            }
          }
          if ((ref1 = response['HostRoles']['state']) === 'INSTALLED' || ref1 === 'STARTED' || ref1 === 'STOPPED') {
            return do_end();
          }
          if ((ref2 = response['HostRoles']['desired_state']) === 'STARTED' || ref2 === 'STOPPED') {
            return do_end();
          }
        }
        opts['method'] = 'PUT';
        opts.content = JSON.stringify({
          RequestInfo: {
            context: `Service Install ${options.component_name} (API)`
          },
          HostRoles: {
            state: 'INSTALLED'
          }
        });
        if (parseInt(statusCode) === 200) {
          if (typeof this.log === "function") {
            this.log({
              message: `PUT Component in INSTALLED state  hostname:${options.hostname} component: ${options.component_name}`,
              level: 'INFO',
              module: 'ryba-ambari-actions/hosts/component_install'
            });
          }
        }
        return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
          var do_wait, request_id;
          request_id = null;
          do_wait = function() {
            opts.path = `/api/v1/clusters/${options.cluster_name}/requests/${request_id}`;
            opts.method = 'GET';
            if (typeof this.log === "function") {
              this.log({
                message: `Wait Request id ${request_id}`,
                level: 'INFO',
                module: 'ryba-ambari-actions/hosts/component_install'
              });
            }
            return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
              try {
                if (err) {
                  throw err;
                }
                response = JSON.parse(response);
                if (statusCode !== 200) {
                  throw Error(response.message);
                }
                if (response['Requests']['request_status'] === 'COMPLETED') {
                  status = true;
                  return do_end();
                }
              } catch (error1) {
                err = error1;
                error = err;
                return do_end();
              }
            });
          };
          try {
            if (err) {
              throw err;
            }
            if (parseInt(statusCode) !== 202) {
              throw Error(response.message);
            }
            response = JSON.parse(response);
            request_id = response['Requests']['id'];
            if (typeof this.log === "function") {
              this.log({
                message: `Install Service ${options.component_name} Accepted with Request id ${request_id}`,
                level: 'INFO',
                module: 'ryba-ambari-actions/hosts/component_install'
              });
            }
            if (statusCode !== 202) {
              throw Error(response.message);
            }
            status = true;
            if (options.wait) {
              return interval = setInterval(do_wait, 2000);
            } else {
              return do_end();
            }
          } catch (error1) {
            err = error1;
            error = err;
            return do_end();
          }
        });
      } catch (error1) {
        err = error1;
        error = err;
        status = false;
        return do_end();
      }
    });
  } catch (error1) {
    err = error1;
    error = err;
    return do_end();
  }
};

// ## Depencendies
utils = require('../utils');
