// Generated by CoffeeScript 2.1.1
// # Ambari Component add to host

// Add a host to an ambari cluster [REST API v2](https://github.com/apache/ambari/blob/trunk/ambari-server/docs/api/v1)
// The node should already exist in ambari.

// * `password` (string)
//   Ambari Administrator password.
// * `url` (string)   
//   Ambari External URL.
// * `username` (string)
//   Ambari Administrator username.
// * `cluster_name` (string)   
//   Name of the cluster, optional
// * `hostnme` (string)   
//   The name of host to add the component to.

// ## Exemple

// ```js
// .hosts.component_add({
//   "username": 'ambari_admin',
//   "password": 'ambari_secret',
//   "url": "http://ambari.server.com",
//   "component_name": 'NAMENODE'
//   "hostname": 'master1.metal.ryba'
//   }
// }, function(err, status){
//   console.log( err ? err.message : "Node Added To Cluster: " + status)
// })
// ```

// ## Source Code
var utils;

module.exports = function(options, callback) {
  var do_end, err, error, hostname, opts, path, port, status;
  error = null;
  status = false;
  if (options.debug == null) {
    options.debug = false;
  }
  do_end = function() {
    if (callback != null) {
      return callback(error, status);
    }
    return new Promise(function(fullfil, reject) {
      if (error != null) {
        reject(error);
      }
      return fullfil(status);
    });
  };
  try {
    if (!options.username) {
      throw Error('Required Options: username');
    }
    if (!options.password) {
      throw Error('Required Options: password');
    }
    if (!options.url) {
      throw Error('Required Options: url');
    }
    if (!options.component_name) {
      throw Error('Required Options: component_name');
    }
    if (!options.hostname) {
      throw Error('Required Options: hostname');
    }
    if (!options.cluster_name) {
      throw Error('Required Options: cluster_name');
    }
    [hostname, port] = options.url.split("://")[1].split(':');
    if (options.sslEnabled == null) {
      options.sslEnabled = options.url.split('://')[0] === 'https';
    }
    path = `/api/v1/clusters/${options.cluster_name}/hosts/${options.hostname}/host_components`;
    opts = {
      hostname: hostname,
      port: port,
      rejectUnauthorized: false,
      headers: utils.headers(options),
      sslEnabled: options.sslEnabled
    };
    opts['method'] = 'GET';
    opts.path = `${path}/${options.component_name}`;
    return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
      try {
        if (err) {
          throw err;
        }
        response = JSON.parse(response);
        if (parseInt(statusCode) === 404) {
          if (options.debug) {
            console.log(`component_name ${options.component_name} not found in ambari server hosts.component_name`);
          }
          opts['method'] = 'POST';
          return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
            try {
              if (err) {
                throw err;
              }
              if (statusCode === 201) {
                status = true;
                return do_end();
              } else {
                response = JSON.parse(response);
                throw Error(response.message);
              }
            } catch (error1) {
              err = error1;
              error = err;
              return do_end();
            }
          });
        } else {
          status = false;
          return do_end();
        }
      } catch (error1) {
        err = error1;
        error = err;
        return do_end();
      }
    });
  } catch (error1) {
    err = error1;
    error = err;
    return do_end();
  }
};

// ## Depencendies
utils = require('../utils');
