// Generated by CoffeeScript 2.3.2
(function() {
  // # Ambari Hosts Wait

  // Wait host to be registered using the [REST API v2](https://github.com/apache/ambari/blob/trunk/ambari-server/docs/api/v1)
  // if host 

  // * `password` (string)
  //   Ambari Administrator password.
  // * `url` (string)   
  //   Ambari External URL.
  // * `username` (string)
  //   Ambari Administrator username.
  // * `cluster_name` (string)   
  //   Name of the cluster, optional
  // * `hostname` (string)   
  //   Hostname of the server to add, required.

  // ## Exemple

  // ```js
  // nikita
  // .cluster.wait({
  //   "username": 'ambari_admin',
  //   "password": 'ambari_secret',
  //   "url": "http://ambari.server.com",
  //   "hostname": 'master1.server.com'
  //   }
  // }, function(err, status){
  //   console.log( err ? err.message : "Policy Created: " + status)
  // })
  // ```

  // ## Source Code
  var utils;

  module.exports = function(options, callback) {
    var do_end, do_request, err, error, hostname, interval, opts, path, port, status, waited;
    if (typeof options.options === 'object') {
      options = options.options;
    }
    error = null;
    status = false;
    if (options.debug == null) {
      options.debug = false;
    }
    interval = null;
    if (options.timeout == null) {
      options.timeout = 10 * 60 * 60 * 1000;
    }
    do_end = function() {
      if (interval != null) {
        clearInterval(interval);
      }
      if (callback != null) {
        return callback(error, status);
      }
      return new Promise(function(fullfil, reject) {
        if (error != null) {
          reject(error);
        }
        return fullfil(status);
      });
    };
    try {
      if (!options.username) {
        throw Error('Required Options: username');
      }
      if (!options.password) {
        throw Error('Required Options: password');
      }
      if (!options.url) {
        throw Error('Required Options: url');
      }
      if (!options.hostname) {
        throw Error('Required Options: hostname');
      }
      [hostname, port] = options.url.split("://")[1].split(':');
      if (options.sslEnabled == null) {
        options.sslEnabled = options.url.split('://')[0] === 'https';
      }
      path = "/api/v1/hosts";
      opts = {
        hostname: hostname,
        port: port,
        rejectUnauthorized: false,
        headers: utils.headers(options),
        sslEnabled: options.sslEnabled
      };
      opts['method'] = 'GET';
      opts.path = `${path}/${options.hostname}`;
      waited = 0;
      if (typeof this.log === "function") {
        this.log({
          message: `Wait Component to be available hostname:${options.hostname} component: ${options.component_name}`,
          level: 'INFO',
          module: 'ryba-ambari-actions/hosts/wait'
        });
      }
      do_request = function() {
        return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
          waited = waited + 1000;
          if (err) {
            throw err;
          }
          response = JSON.parse(response);
          if ((response != null ? response.status : void 0) === 404) {
            if (options.debug) {
              console.log(`host ${options.hostname} not found in ambari server host.wait`);
            }
            if (waited > options.timeout) {
              throw Error(`Timeout waiting for host ${options.hostname} to be registered`);
            }
          } else {
            status = true;
            return do_end();
          }
        });
      };
      if (typeof this.log === "function") {
        this.log({
          message: "Set Wait Interval 5000ms",
          level: 'INFO',
          module: 'ryba-ambari-actions/hosts/wait'
        });
      }
      return interval = setInterval(do_request, 1000);
    } catch (error1) {
      err = error1;
      error = err;
      return do_end();
    }
  };

  // ## Depencendies
  utils = require('../utils');

}).call(this);
