// Generated by CoffeeScript 2.1.1
// # Ambari Cluster host Delete

// Create a cluster using the [REST API v2](https://github.com/apache/ambari/blob/trunk/ambari-server/docs/api/v1)

// * `password` (string)
//   Ambari Administrator password.
// * `url` (string)   
//   Ambari External URL.
// * `username` (string)
//   Ambari Administrator username.
// * `cluster_name` (string)   
//   Name of the cluster, optional
// * `hostname` (string)   
//   Hostname of the server to add, required.

// ## Exemple

// ```js
// cluster.node_delete({
//   "username": 'ambari_admin',
//   "password": 'ambari_secret',
//   "url": "http://ambari.server.com",
//   "cluster_name": 'my_cluster'
//   "hostname": 'server1.server.com'
//   }
// }, function(err, status){
//   console.log( err ? err.message : "Node Deleted From Cluster: " + status)
// })
// ```

// ## Source Code
var utils;

module.exports = function(options, callback) {
  var do_end, err, error, hostname, opts, path, port, status;
  error = null;
  status = false;
  if (options.debug == null) {
    options.debug = false;
  }
  do_end = function() {
    if (callback != null) {
      return callback(error, status);
    }
    return new Promise(function(fullfil, reject) {
      if (error != null) {
        reject(error);
      }
      return fullfil(status);
    });
  };
  try {
    if (!options.username) {
      throw Error('Required Options: username');
    }
    if (!options.password) {
      throw Error('Required Options: password');
    }
    if (!options.url) {
      throw Error('Required Options: url');
    }
    if (!options.hostname) {
      throw Error('Required Options: hostname');
    }
    if (!options.cluster_name) {
      throw Error('Required Options: cluster_name');
    }
    [hostname, port] = options.url.split("://")[1].split(':');
    if (options.sslEnabled == null) {
      options.sslEnabled = options.url.split('://')[0] === 'https';
    }
    path = `/api/v1/clusters/${options.cluster_name}/hosts`;
    opts = {
      hostname: hostname,
      port: port,
      rejectUnauthorized: false,
      headers: utils.headers(options),
      sslEnabled: options.sslEnabled
    };
    opts['method'] = 'GET';
    opts.path = `${path}/${options.hostname}`;
    return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
      if (err) {
        throw err;
      }
      response = JSON.parse(response);
      if ((response != null ? response.status : void 0) === 404) {
        if (options.debug) {
          console.log(`node ${options.hostname} not found in ambari server cluster.node_delete`);
        }
        status = false;
        return do_end();
      } else {
        opts['method'] = 'DELETE';
        return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
          if (err) {
            throw err;
          }
          status = true;
          return do_end();
        });
      }
    });
  } catch (error1) {
    err = error1;
    error = err;
    return do_end();
  }
};

// ## Depencendies
utils = require('../utils');
