// Generated by CoffeeScript 2.1.1
// # Ambari Configs update

// Get ambari named config using the [REST API v2](https://github.com/apache/ambari/blob/trunk/ambari-server/docs/api/v1)

// * `password` (string)
//   Ambari Administrator password.
// * `url` (string)   
//   Ambari External URL.
// * `username` (string)
//   Ambari Administrator username.
// * `cluster_name` (string)   
//   Name of the cluster, required
// * `config_type` (string)   
//   config of the name to modify example core-site, hdfs-site... required.
// * `properties` (object)   
//   properties to add to the configuration, required.
// * `tag` (object)   
//   tag of the updated config, will be computed if no provided.

// ## Exemple

// ```js
// configs.get({
//   "username": 'ambari_admin',
//   "password": 'ambari_secret',
//   "url": "http://ambari.server.com",
//   "config_type": 'hdfs-site'
//   }
// }, function(err, status, properties){
//   console.log( err ? err.message : "Properties are: " + properties)
// })
// ```
var utils;

module.exports = function(options, callback) {
  var do_end, err, error, hostname, opts, path, port, properties, status;
  error = null;
  properties = null;
  status = false;
  if (options.debug == null) {
    options.debug = false;
  }
  do_end = function() {
    if (callback != null) {
      callback(error, status, properties);
    }
    return new Promise(function(fullfil, reject) {
      if (error != null) {
        reject(error);
      }
      return fullfil(properties);
    });
  };
  try {
    if (!options.username) {
      throw Error('Required Options: username');
    }
    if (!options.password) {
      throw Error('Required Options: password');
    }
    if (!options.url) {
      throw Error('Required Options: url');
    }
    if (!options.cluster_name) {
      throw Error('Required Options: cluster_name');
    }
    if (!options.config_type) {
      throw Error('Required Options: config_type');
    }
    if (!options.tag) {
      throw Error('Required Options: tag');
    }
    [hostname, port] = options.url.split("://")[1].split(':');
    if (options.sslEnabled == null) {
      options.sslEnabled = options.url.split('://')[0] === 'https';
    }
    path = `/api/v1/clusters/${options.cluster_name}/configurations?type=${options.config_type}&tag=${options.tag}`;
    opts = {
      hostname: hostname,
      port: port,
      rejectUnauthorized: false,
      headers: utils.headers(options),
      sslEnabled: options.sslEnabled
    };
    opts['method'] = 'GET';
    opts.path = `${path}`;
    return utils.doRequestWithOptions(opts, function(err, statusCode, response) {
      var items, result;
      if (err) {
        throw err;
      }
      result = JSON.parse(response);
      if (statusCode !== 200) {
        throw Error('Properties not found');
      }
      items = result.items.filter(function(item) {
        return item.tag === options.tag && item.type === options.config_type;
      });
      if (!(items.length > 0)) {
        throw Error(`${options.config_type} not found with tag ${options.tag}`);
      }
      properties = items[0].properties;
      status = true;
      return do_end();
    });
  } catch (error1) {
    err = error1;
    error = err;
    return do_end();
  }
};

// ## Depencendies
utils = require('../utils');
